source 'https://rubygems.org'

ruby '>= 2.6.6', '< 2.7.0'
gem 'rails', '4.2.10'

group :development do
  gem 'web-console', '~> 2.0'
end

# for Heroku deployment

group :development, :test do
  gem 'sqlite3', '1.3.11'
  gem 'bcrypt', '~> 3.1.2'
  gem 'byebug'
  gem 'database_cleaner', '1.4.1'
  gem 'capybara', '2.5.0'
  gem 'launchy'
  gem 'rspec-rails', '3.7.2'
  gem 'ZenTest', '4.11.2'
  gem "rerun", git: "https://github.com/alexch/rerun.git"
end

group :test do
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'
  gem 'simplecov', :require => false
  gem 'phantomjs', :require => 'phantomjs/poltergeist'
  gem 'capybara', '2.5.0'
  gem 'poltergeist', '~> 1.6.0'
  gem 'selenium-webdriver', '~> 2.40.0'
  gem 'chromedriver-helper', '~> 2.1.0'
end
group :production do
  gem 'pg', '~> 0.18'
  gem 'rails_12factor'
end

# Gems used only for assets and not required
# in production environments by default.

gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '>= 2.7.1'
gem 'jquery-rails'
gem 'groupdate' # optional
gem 'apexcharts'
gem "jquery-ui-rails"
gem 'figaro'
gem 'best_in_place'
